### ISSUE TITLE
How to Support this Project?

### ISSUE THREAD

**Issue by hyperxpro** [nixxcode/jvm-brotli#31]
Really appreciate all the hard work. I would be happy to support this project. 
How can I get you a coffee? Please add the "Sponsor" tab in this repository. 

Cheers!

**Comment by nixxcode** [comment]
Hi there!

Thank you very much for the kind, encouraging words.

It's my first open source project, so I never even considered support/sponsorship, but I will look into getting that set up.

Again, thank you :)
